# Generated by Django 4.2.6 on 2025-06-28 21:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_monthlysalary_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalary',
            name='paid_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
