# Generated by Django 4.2.6 on 2025-07-11 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_monthlysalary_paid_date_position_job_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Company address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Company email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_code',
            field=models.CharField(max_length=200, verbose_name='Company tax code'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Department name'),
        ),
        migrations.AlterField(
            model_name='department',
            name='parent_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.department', verbose_name='Parent department'),
        ),
        migrations.AlterField(
            model_name='position',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='position',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='position',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='Is manager'),
        ),
        migrations.AlterField(
            model_name='position',
            name='job_description',
            field=models.TextField(verbose_name='Job Description'),
        ),
        migrations.AlterField(
            model_name='position',
            name='job_description_en',
            field=models.TextField(null=True, verbose_name='Job Description'),
        ),
        migrations.AlterField(
            model_name='position',
            name='job_description_uk',
            field=models.TextField(null=True, verbose_name='Job Description'),
        ),
        migrations.AlterField(
            model_name='position',
            name='monthly_rate',
            field=models.IntegerField(default=0, verbose_name='Monthly rate'),
        ),
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='position',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='position',
            name='title_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
    ]
