# Generated by Django 4.2.6 on 2025-07-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_alter_company_address_alter_company_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Department name'),
        ),
        migrations.AddField(
            model_name='department',
            name='name_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='Department name'),
        ),
    ]
