# Generated by Django 4.2.6 on 2025-07-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_employee_avatar_employee_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ImageField',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
    ]
