# Generated by Django 4.2.6 on 2025-07-18 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_company_imagefield'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='ImageField',
            new_name='logo',
        ),
    ]
